###################################################################

# Created by write_sdc on Tue Sep 22 15:24:45 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_load -pin_load 5 [get_ports {acc_out[31]}]
set_load -pin_load 5 [get_ports {acc_out[30]}]
set_load -pin_load 5 [get_ports {acc_out[29]}]
set_load -pin_load 5 [get_ports {acc_out[28]}]
set_load -pin_load 5 [get_ports {acc_out[27]}]
set_load -pin_load 5 [get_ports {acc_out[26]}]
set_load -pin_load 5 [get_ports {acc_out[25]}]
set_load -pin_load 5 [get_ports {acc_out[24]}]
set_load -pin_load 5 [get_ports {acc_out[23]}]
set_load -pin_load 5 [get_ports {acc_out[22]}]
set_load -pin_load 5 [get_ports {acc_out[21]}]
set_load -pin_load 5 [get_ports {acc_out[20]}]
set_load -pin_load 5 [get_ports {acc_out[19]}]
set_load -pin_load 5 [get_ports {acc_out[18]}]
set_load -pin_load 5 [get_ports {acc_out[17]}]
set_load -pin_load 5 [get_ports {acc_out[16]}]
set_load -pin_load 5 [get_ports {acc_out[15]}]
set_load -pin_load 5 [get_ports {acc_out[14]}]
set_load -pin_load 5 [get_ports {acc_out[13]}]
set_load -pin_load 5 [get_ports {acc_out[12]}]
set_load -pin_load 5 [get_ports {acc_out[11]}]
set_load -pin_load 5 [get_ports {acc_out[10]}]
set_load -pin_load 5 [get_ports {acc_out[9]}]
set_load -pin_load 5 [get_ports {acc_out[8]}]
set_load -pin_load 5 [get_ports {acc_out[7]}]
set_load -pin_load 5 [get_ports {acc_out[6]}]
set_load -pin_load 5 [get_ports {acc_out[5]}]
set_load -pin_load 5 [get_ports {acc_out[4]}]
set_load -pin_load 5 [get_ports {acc_out[3]}]
set_load -pin_load 5 [get_ports {acc_out[2]}]
set_load -pin_load 5 [get_ports {acc_out[1]}]
set_load -pin_load 5 [get_ports {acc_out[0]}]
set_load -pin_load 5 [get_ports overflow]
create_clock [get_ports clk]  -period 10000  -waveform {0 5000}
set_clock_uncertainty 100  [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_input_delay -clock clk  1000  [get_ports enable]
set_input_delay -clock clk  1000  [get_ports {data_in[31]}]
set_input_delay -clock clk  1000  [get_ports {data_in[30]}]
set_input_delay -clock clk  1000  [get_ports {data_in[29]}]
set_input_delay -clock clk  1000  [get_ports {data_in[28]}]
set_input_delay -clock clk  1000  [get_ports {data_in[27]}]
set_input_delay -clock clk  1000  [get_ports {data_in[26]}]
set_input_delay -clock clk  1000  [get_ports {data_in[25]}]
set_input_delay -clock clk  1000  [get_ports {data_in[24]}]
set_input_delay -clock clk  1000  [get_ports {data_in[23]}]
set_input_delay -clock clk  1000  [get_ports {data_in[22]}]
set_input_delay -clock clk  1000  [get_ports {data_in[21]}]
set_input_delay -clock clk  1000  [get_ports {data_in[20]}]
set_input_delay -clock clk  1000  [get_ports {data_in[19]}]
set_input_delay -clock clk  1000  [get_ports {data_in[18]}]
set_input_delay -clock clk  1000  [get_ports {data_in[17]}]
set_input_delay -clock clk  1000  [get_ports {data_in[16]}]
set_input_delay -clock clk  1000  [get_ports {data_in[15]}]
set_input_delay -clock clk  1000  [get_ports {data_in[14]}]
set_input_delay -clock clk  1000  [get_ports {data_in[13]}]
set_input_delay -clock clk  1000  [get_ports {data_in[12]}]
set_input_delay -clock clk  1000  [get_ports {data_in[11]}]
set_input_delay -clock clk  1000  [get_ports {data_in[10]}]
set_input_delay -clock clk  1000  [get_ports {data_in[9]}]
set_input_delay -clock clk  1000  [get_ports {data_in[8]}]
set_input_delay -clock clk  1000  [get_ports {data_in[7]}]
set_input_delay -clock clk  1000  [get_ports {data_in[6]}]
set_input_delay -clock clk  1000  [get_ports {data_in[5]}]
set_input_delay -clock clk  1000  [get_ports {data_in[4]}]
set_input_delay -clock clk  1000  [get_ports {data_in[3]}]
set_input_delay -clock clk  1000  [get_ports {data_in[2]}]
set_input_delay -clock clk  1000  [get_ports {data_in[1]}]
set_input_delay -clock clk  1000  [get_ports {data_in[0]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[31]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[30]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[29]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[28]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[27]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[26]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[25]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[24]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[23]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[22]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[21]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[20]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[19]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[18]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[17]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[16]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[15]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[14]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[13]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[12]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[11]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[10]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[9]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[8]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[7]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[6]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[5]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[4]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[3]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[2]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[1]}]
set_output_delay -clock clk  1000  [get_ports {acc_out[0]}]
set_output_delay -clock clk  1000  [get_ports overflow]
set_input_transition -max 50  [get_ports rst_n]
set_input_transition -min 50  [get_ports rst_n]
set_input_transition -max 50  [get_ports enable]
set_input_transition -min 50  [get_ports enable]
set_input_transition -max 50  [get_ports {data_in[31]}]
set_input_transition -min 50  [get_ports {data_in[31]}]
set_input_transition -max 50  [get_ports {data_in[30]}]
set_input_transition -min 50  [get_ports {data_in[30]}]
set_input_transition -max 50  [get_ports {data_in[29]}]
set_input_transition -min 50  [get_ports {data_in[29]}]
set_input_transition -max 50  [get_ports {data_in[28]}]
set_input_transition -min 50  [get_ports {data_in[28]}]
set_input_transition -max 50  [get_ports {data_in[27]}]
set_input_transition -min 50  [get_ports {data_in[27]}]
set_input_transition -max 50  [get_ports {data_in[26]}]
set_input_transition -min 50  [get_ports {data_in[26]}]
set_input_transition -max 50  [get_ports {data_in[25]}]
set_input_transition -min 50  [get_ports {data_in[25]}]
set_input_transition -max 50  [get_ports {data_in[24]}]
set_input_transition -min 50  [get_ports {data_in[24]}]
set_input_transition -max 50  [get_ports {data_in[23]}]
set_input_transition -min 50  [get_ports {data_in[23]}]
set_input_transition -max 50  [get_ports {data_in[22]}]
set_input_transition -min 50  [get_ports {data_in[22]}]
set_input_transition -max 50  [get_ports {data_in[21]}]
set_input_transition -min 50  [get_ports {data_in[21]}]
set_input_transition -max 50  [get_ports {data_in[20]}]
set_input_transition -min 50  [get_ports {data_in[20]}]
set_input_transition -max 50  [get_ports {data_in[19]}]
set_input_transition -min 50  [get_ports {data_in[19]}]
set_input_transition -max 50  [get_ports {data_in[18]}]
set_input_transition -min 50  [get_ports {data_in[18]}]
set_input_transition -max 50  [get_ports {data_in[17]}]
set_input_transition -min 50  [get_ports {data_in[17]}]
set_input_transition -max 50  [get_ports {data_in[16]}]
set_input_transition -min 50  [get_ports {data_in[16]}]
set_input_transition -max 50  [get_ports {data_in[15]}]
set_input_transition -min 50  [get_ports {data_in[15]}]
set_input_transition -max 50  [get_ports {data_in[14]}]
set_input_transition -min 50  [get_ports {data_in[14]}]
set_input_transition -max 50  [get_ports {data_in[13]}]
set_input_transition -min 50  [get_ports {data_in[13]}]
set_input_transition -max 50  [get_ports {data_in[12]}]
set_input_transition -min 50  [get_ports {data_in[12]}]
set_input_transition -max 50  [get_ports {data_in[11]}]
set_input_transition -min 50  [get_ports {data_in[11]}]
set_input_transition -max 50  [get_ports {data_in[10]}]
set_input_transition -min 50  [get_ports {data_in[10]}]
set_input_transition -max 50  [get_ports {data_in[9]}]
set_input_transition -min 50  [get_ports {data_in[9]}]
set_input_transition -max 50  [get_ports {data_in[8]}]
set_input_transition -min 50  [get_ports {data_in[8]}]
set_input_transition -max 50  [get_ports {data_in[7]}]
set_input_transition -min 50  [get_ports {data_in[7]}]
set_input_transition -max 50  [get_ports {data_in[6]}]
set_input_transition -min 50  [get_ports {data_in[6]}]
set_input_transition -max 50  [get_ports {data_in[5]}]
set_input_transition -min 50  [get_ports {data_in[5]}]
set_input_transition -max 50  [get_ports {data_in[4]}]
set_input_transition -min 50  [get_ports {data_in[4]}]
set_input_transition -max 50  [get_ports {data_in[3]}]
set_input_transition -min 50  [get_ports {data_in[3]}]
set_input_transition -max 50  [get_ports {data_in[2]}]
set_input_transition -min 50  [get_ports {data_in[2]}]
set_input_transition -max 50  [get_ports {data_in[1]}]
set_input_transition -min 50  [get_ports {data_in[1]}]
set_input_transition -max 50  [get_ports {data_in[0]}]
set_input_transition -min 50  [get_ports {data_in[0]}]
set_false_path   -from [get_ports rst_n]
